### ISSUE TITLE
auto excerpt

### ISSUE THREAD

**Issue by tparnell8** [LouisBarranqueiro/hexo-theme-tranquilpeak#153]
Pre 1.4 the posts on the home page (list view) would cut off and a continue reading link would appear. In 1.4 you introduced the `<!-- more -->` and excerpt feature. Could you also add an auto excerpt setting in the config file that defines a character (or word) count to get the excerpt from if no tags are provided? I ask because I like my blog to have the cut off in the words, but I have a lot of posts and it would take quite some time to add the tag in each one.

**Comment by LouisBarranqueiro** [comment]
I removed this feature in 1.4 to give to user more possibilities. Not sure, that this feature is very useful, but ok since I removed this feature maybe prematurely, i'm gonna add a variable to activate and set number of character for auto excerpt.

**Comment by tparnell8** [comment]
So I'll tell you my use case...

Newer blog posts I can use the excerpt and more tags. I like all the posts to have a "Continue reading" link in the list page. I do like the more and excerpt feature, but I'd like an auto max character excerpt setting as well if possible.

it would not be trivial to go back and do the same to my older posts hence the request.

**Comment by LouisBarranqueiro** [comment]
there is a problem : when there is no comments (more and excerpt), it automatically display all post content. So, do you want a variable in `_config.yml` or in post front-matter to overwrite this feature?

**Comment by LouisBarranqueiro** [comment]
I can add `autoExcerpt` var (true|false) in front matter to overwrite default behavior. And you will have to set ,`autoExerpt: true` in your old posts. Do you have a better idea and this one is good to you?

**Comment by tparnell8** [comment]
variable in _config.yml

**Comment by tparnell8** [comment]
sorry I only just saw this

**Comment by LouisBarranqueiro** [comment]
why a variable in configuration file since you wanna use auto excerpt for previous post and exceprt and more tag for newer. It can't works because if there are no tags (excerpt or more), the post content will be displayed, that's why, you need a variable in front-matter to specify if you want an auto excerpt

**Comment by tparnell8** [comment]
front matter is fine...I am just trying to avoid editing multiple files but I guess I can just control + shift + h the files

**Comment by LouisBarranqueiro** [comment]
you will be forced to update front-matter of our files because now, when there is no tags, it display by default the entire content. that's why, i'm gonna allow you to specify in front-matter (`autoExcerpt: True`) to cut automatically the post. I'm on :)

**Comment by tparnell8** [comment]
ah cool sounds great

**Comment by LouisBarranqueiro** [comment]
Hey, man instead of re-add this feature, I developed a migrator, to migrate your old posts (Tranquilpeak < 1.4.0) to Tranquilpeak >= 1.4.0. It add `<!-- excerpt -->` tag in all posts where there is no excerpt tag (excerpt or more). I'm gonna release this migrator in Tranquilpeak 1.7.0 this friday. Check it here : [1.4.0.js](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/1.7.0-migrator/scripts/migrators/1.4.0.js)
