### ISSUE TITLE
In tag page , the disqus has been loaded

### ISSUE THREAD

**Issue by imochen** [LouisBarranqueiro/hexo-theme-tranquilpeak#181]
I use `hexo new page "tags"` create a tag page.
With the content
```
title: "tags"
layout: "all-tags"
---
```
In this page , I found a mistake 
```
Uncaught TypeError: Cannot read property 'appendChild' of null
```
that seems like because `post.comments` is `true` in `script.ejs`.

```
<% if (post.comments) { %>
    //...
<% } %>
```

In archives page and categories `post.comments` is `false`.

I have change it to 
```
<% if (post.comments && post.layout !== 'all-archives' && post.layout !== 'all-tags' && post.layout !== 'all-categories') { %>
    //...
<% } %>
```
But I want to know why `post.comments` in tags page is `false`.

thx a lot .

**Comment by LouisBarranqueiro** [comment]
Put `comments: false` in **all-archives**, **all-tags** and **archive** page. instead of edit the code. I will edit user documentation. 

It disable because I decided to :D I think that enable comments on this page is useless. But if you wanna enable them, I can update the code in v1.5.1. It's a yes? :)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.6.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.6.0) is released and solve this issue
