### ISSUE TITLE
How to edit the about page?

### ISSUE THREAD

**Issue by whix** [LouisBarranqueiro/hexo-theme-tranquilpeak#199]
I had used your hexo theme, thank you very much!
I read the user document,  but I didn't find how to edit the about page for myself. I am not good at frontend technology, so I come here to ask for solution.

**Comment by LouisBarranqueiro** [comment]
what do you means by "edit"? what do you want to change?

**Comment by hoverwinter** [comment]
I meet the same problem. There are literal **author.bio** and **author.job** without substitution when I add bio and job in `_config.xml` of both hexo and the theme. I found the code in the file `about.ejs` :

        <% if (__('author.bio')) { %>
            <h5 id="about-card-bio"><%- markdown(__('author.bio')) %></h5>
        <% } %>
        <% if (__('author.job')) { %>

But I don't understand the meaning of `__('author.job')`.

So the problem is: how to make the `author.job` etc. of my custom content.

**Comment by hoverwinter** [comment]
I find the location to modify author.bio & author.job.

`themes/tranquilpeak/languages/xxx.yml`

at the end of the file.

**Comment by LouisBarranqueiro** [comment]
Hey man! It's written in the [user documentation](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#author) :)

**Comment by hoverwinter** [comment]
Yeah, thank you! :)  But it's really easy to be ignored for not being associated with About page.
