### ISSUE TITLE
Shall display post images to mobile users?

### ISSUE THREAD

**Issue by LimiQS** [LouisBarranqueiro/hexo-theme-tranquilpeak#206]
I found no Post Thumbnail Images (Featured Images) displayed when browsing the homepage of the theme when using a mobile phone browser but the images are still being requested (if my chrome Developer Tools has nothing went wrong, these images are just HIDDEN by some CSS but not REMOVED by mobile-optimized HTML). So if there are any way to let them displayed (since they are already 'loaded' and it's hard to create an independent page for mobile)? I found it's not a good idea to simply remove "display:none;".

**Comment by LouisBarranqueiro** [comment]
Hi man. it's a static site. the only way to do that is to implement an app (server side) that check that the request is sent by a mobile and then build and return specific page without images. And if you wanna do that on client side with javascript, it will be too late because all other assets will be already downloaded.

**Comment by LimiQS** [comment]
Humm...That's a sad news. By the way, if there are anyway to display and layout featured images properly? By tweaking to CSS files on server side. I think some visitors may hope to share the same 'colourful world' with PC users.

**Comment by LouisBarranqueiro** [comment]
what do you means?

**Comment by LimiQS** [comment]
Display Featured Images for mobile users.

**Comment by LouisBarranqueiro** [comment]
So sorry man, I forget you!!! you just have to edit CSS to display image and re-organize the page style
