### ISSUE TITLE
Image Gallery Suggestion and Query

### ISSUE THREAD

**Issue by t3chguy** [LouisBarranqueiro/hexo-theme-tranquilpeak#214]
Using the `photos` variable in front-matter allows for a simple fancybox image gallery, but it will use the large images as thumbnails for the preview of the gallery. Ability to specify thumbnail locations would be handy.
Also, using the image tag with fancybox `{% image fancybox...` I cannot get the images to link into a gallery, though the example here http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2014/10/29/Tags-plugins-showcase/#Image_%28image%29 manages to link all the car photos into a gallery. I would love to know how to go about doing this myself. Seems as though the gallery is only formed when using the URLs that the images in the example use, copying the tag and changing to my own image breaks this.

Thanks

**Comment by LouisBarranqueiro** [comment]
Hi man. I was in holidays sorry for waiting. :D Yeah, that's a good idea, I had already think about that, if you need it, i'm gonna implement it :)

On the demo site, images are grouped because their link have the same domain. otherwise fancyboxes must have the same `rel` attribute to be grouped. i'm gonna implement this feature to allow you to group images using image tag :)

**Comment by t3chguy** [comment]
Cheers, even if it grouped all relative images together it'd be neat. (Ones which don't start with a domain, and thus get pointed relatively to the current url)
