### ISSUE TITLE
How can I deploy your all-Categories or all-tags in other theme?

### ISSUE THREAD

**Issue by Jeffrey95** [LouisBarranqueiro/hexo-theme-tranquilpeak#215]
What a nice theme it is!
I like your theme very much,especially the all-categories pages and all-tags pages. I would like deploy an similar pages in my blog and I don't want to change my theme. I had tried to configure `all-categories.ejs` ,`all-categories.ejs` in my theme's layout, and had added 'categories-filter.js' and 'categories-filter.js' in `/source/js`. Also, I tried to configure my 'head.ejs'  according to yours,but it seems it doesn't work well. The search function doesn't work. Addtionly, the css seems doesn't work either. :fearful: It look like this now
![myblog](http://7xjfag.com1.z0.glb.clouddn.com/tags.png)
can you give me some guides and tell me we i need to change or add in my theme? Thx a lot.

**Comment by LouisBarranqueiro** [comment]
Hi man! I can't give you an answer since, I don't know the other theme. This question is too large. 

Simple answer : 
- add `all-categories.ejs` template in the other theme
- add `all-categories` page in `source`
- import js feature `categories-filter.js` in the right template
- import all css style referenced in this template

and if it doesn't work, then open browser console to debug
