### ISSUE TITLE
bottom bar border

### ISSUE THREAD

**Issue by LaureKamalandua** [LouisBarranqueiro/hexo-theme-tranquilpeak#227]
When removing borders defined on the bottom-bar; I can't seem to get rid of the bottom bar's white bottom border. Where is it defined? I've checked if some bottom margins where inappropriately defined, but at the first sight. 

![2016-03-01 19_36_36-start](https://cloud.githubusercontent.com/assets/12623827/13437558/322d4f5e-dfe5-11e5-828f-0871642c69e5.png)

![2016-03-01 19_37_01-](https://cloud.githubusercontent.com/assets/12623827/13437555/2f2d0786-dfe5-11e5-9df7-2ee9ac0b2c84.png)

**Comment by LouisBarranqueiro** [comment]
Hey, this bug come from the `share-options-bar` div which is 1px over `bottom-bar` div. I didn't notice this bug since bottom bar is white and share options bar too :D

Go in `source/_css/components/_share-options-bar.scss` and edit the line 3  with     `bottom: -156px;` because height plus border-top = 155px + 1px = 156px

**Comment by LaureKamalandua** [comment]
thanks, that entirely fixed it :+1:
