### ISSUE TITLE
add a feature to change the sharing options list

### ISSUE THREAD

**Issue by LouisBarranqueiro** [LouisBarranqueiro/hexo-theme-tranquilpeak#314]
In theme configuration file, give possibility to choose which share option to add at the bottom of an article. like this :  

``` yml
sharing_options:
    - facebook
        - fa-facebook #font awesome icon  
    - twitter
        - fa-twitter #font awesome icon  
    - wechat
        - fa-wechat #font awesome icon  
```

 But I need your help :)

Could you give me the main list of all social networks and platforms that china users use to share content, please? I need the name of the social networks and the share link.
E.g : 
- **Facebook** : https://www.facebook.com/sharer/sharer.php?u={{post.permalink}}
- **Twitter** : https://twitter.com/intent/tweet?text={{post.permalink}}

**Comment by HIKALU-Z** [comment]
thanks for your help
this is the list

- **weibo(like twitter in china):** http://service.weibo.com/share/share.php?&title={{post.permalink}}

the font is `fa-weibo`

- **wechat(like Line)**  
this is the most popular social app in china but now i still not find how to share link frome outside of the app. it can only share link inside of the app. i am try to generate  two-dimensional code of the post.permalink and when you click the share buttton it can appear like a modal hover on the button.


- **zhihu(like quera)** www.zhihu.com

i know it is strange ，but many chinese people do their social at this website like quera.
maybe it just need put a link at menu 

-**renren(like facebook)** 

this site was pupular 2years ago ,but now only few people use it 
so i think there is no need to creat this share link

i am sorry i am a new to hexo and frontend otherwise maybe i can more helpful to you

**Comment by abelsu7** [comment]
Besides @HIKALU-Z mentioned, the following social networks are popular in China as well -
* **QQ**: http://connect.qq.com/widget/shareqq/index.html?url={{post.permalink}}&title={{post.title}}
<br />The icon of QQ is `fa-qq`, and user can pick one(or several) friend from QQ's friends list to share the link with.

* **Qzone**: http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url={{post.permalink}}
<br />It's a pity that FontAwesome doesn't include the icon of [Qzone](http://qzone.qq.com). So I use `fa-star` instead.

By the way, there is a sharing service provider called [JiaThis](http://www.jiathis.com) which integrates almost all popular sharing links into itself. You can take it as a reference. (However, it seems that [JiaThis](http://www.jiathis.com) doen't have an English website)

**Comment by abelsu7** [comment]
Hey bro,

I tried JiaThis in my hexo blog just now. And in my point of view, it's so cool and easy enough for you to integrate into Tranquilpeak! You can visit [my blog](http://abelsu7.cn) and look through any post to see the behavior.

I strongly recommend you to use [sidebar code style for JiaThis](http://www.jiathis.com/getcode), because only one-line javascript code will provide you with about 100 popular social networks in China and as a floating sidebar, it won't change the layout of Tranquilpeak.

To use it in your theme, just add the following code into `tranquilpeak/layout/_partial/post.ejs`. 

```javascript
<!-- JiaThis Button BEGIN -->
<script type="text/javascript" src="http://v3.jiathis.com/code/jiathis_r.js?move=0" charset="utf-8"></script>
<!-- JiaThis Button END -->
```

You can comment these code and allow Chinese user to decide whether to use JiaThis.

So happy to see Tranquilpeak developed with concern about Chinese users. Thanks you anyway : )

**Comment by abelsu7** [comment]
Recently it's popular among some Chinese users, but I'm not sure.

If so, you can use Weibo, QQ, Qzone, Renren for your sharing options list, and their sharing links have been mentioned above. 

[Zhihu](https://www.zhihu.com), [Douban](https://www.douban.com) and [Baidu Tieba](http://tieba.baidu.com) is also popular in China, but I can't find sharing link for the first one and the fontawesome icons are lack for the rest.

As for Wechat, the most popular app in China, the usual sharing method is showing an QR code of this post, but I don't know how to achieve it LOL.

**Comment by HIKALU-Z** [comment]
i think the share-option has weibo and wechat is enough to chinses users .but i am still thinking how to add a link of wechat  .Maybe i have to do like the picture.
![image](https://cloud.githubusercontent.com/assets/14190574/17360383/eacffd40-599d-11e6-88af-fa28958784ac.png)

**Comment by LouisBarranqueiro** [comment]
ok, to sum up, we have : 
- Facebook
- Twitter
- Google +
- LinkedIn
- Weibo
- QQ
- Qzone
- renren

**Comment by aerohub** [comment]
Hello there! Two largest Russian networks:

- **VK**: `https://vk.com/share.php?url={{post.permalink}}` and icon `fa-vk`
- **Odnoklassniki**: `https://connect.ok.ru/offer?url={{post.permalink}}` and icon `fa-odnoklassniki`

**Comment by LouisBarranqueiro** [comment]
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.10.0
