### ISSUE TITLE
tag link in tags page didn't work

### ISSUE THREAD

**Issue by toughpeter** [LouisBarranqueiro/hexo-theme-tranquilpeak#321]
Hi LouisBarranqueiro, thanks for your awesome hexo theme!
I am using it to build my blog.
I found some problem when I use "tag link" in "tags page".
This is my first time posting Issues on Github.
Please let me know if I can help or I just misunderstood the feature.
- **Operating system with version** : Mac OX X El Capitan 10.11.6
- **Node version** : 5.5.0
- **Hexo version** : 3.2.2
- **Hexo-cli version** : 
- **Tranquilpeak version** : 1.8.0 origin
### Actual behavior

The url will became "/all-tags/#animal-list" but the content still the same as "/all-tags".
### Expected behavior

Change url to "/all-tags/#animal-list" and shows only the articles which have the "animal" tag in the list
### Steps to reproduce the behavior
1. Go to /all-tags/ page by clicking "tags" link on sidebar
2. All the tags will be listed under the block of search input
3. Click one of the tag, let's say "animals"
4. The url will became "/all-tags/#animal-list" but the content still the same.

**Comment by LouisBarranqueiro** [comment]
Hey @toughpeter,

It's the normal behavior. When you click on a "tag" button, it goes to the list of posts of this tag. That's why it add and anchor in url. 
![capture d ecran 2016-08-17 a 20 32 38](https://cloud.githubusercontent.com/assets/4705626/17748469/d2a55e3c-64b9-11e6-9520-cda3d37f1088.png)

The link to display only the articles which have a specified tag is at the top of the list of posts
![capture d ecran 2016-08-17 a 20 32 48](https://cloud.githubusercontent.com/assets/4705626/17748476/d98c98c8-64b9-11e6-85cd-dfbdabc99d8c.png)
