### ISSUE TITLE
BUG: 404 error links for persian sites

### ISSUE THREAD

**Issue by Mr0Null** [LouisBarranqueiro/hexo-theme-tranquilpeak#328]
one problem is the jalali calendar! I want to use moment-jalaali, but i couldn't! also other problem is in all-archive, moment is parsing persian digits for links (uses ۰۶ instead of 06 so it causes 404!)

**Comment by LouisBarranqueiro** [comment]
Please provide more information about this issue. Did you find a way to fix it? at theme level? at Hexo level?

**Comment by Mr0Null** [comment]
I didn't find way to fix it :( but I think the problem is with moment while parsing date so it uses persian numbers instead of english ones!

**Comment by LouisBarranqueiro** [comment]
Yeah, it definitely come from moment, because it doesn't support this calendar by default. That why you need a plugin. This issue must be fixed at Hexo level and not in theme. I don't wanna try to find a workaround at theme level, it's not relevant. Create an issue on their repository to ask to support this calendar.
