### ISSUE TITLE
Highlighted code is ugly

### ISSUE THREAD

**Issue by wigile** [LouisBarranqueiro/hexo-theme-tranquilpeak#392]
Check your demo @LouisBarranqueiro 

http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2015/03/23/highlighted-code-showcase/

**Comment by LouisBarranqueiro** [comment]
?

**Comment by wigile** [comment]
I'm sorry, my last question is not constructived.

In my computer (online), your highlighted code font-family "Menlo" is not visible in my browser.  However, it's fixed after menlo font installed in my computer. I see you do not import directly the menlo font in utils/mixins/_font.scss.

Any idea?

**Comment by darekkay** [comment]
Since you don't provide a fallback monospace font, this is how codeblocks look like, when you don't have *Menlo* installed (which it isn't by default, at least on Windows):

![image](https://cloud.githubusercontent.com/assets/3101914/24076145/16f29466-0c2a-11e7-8926-4d33251638e5.png)

Define `$monospace` as `Menlo,  monospace` to prevent this from happening. 
Incuding Menlo is also an option, but a monospace fallback is still a good idea, in case users block web fonts.

**Comment by jrbenito** [comment]
Hi,

On dev branch it was already done:

`./utils/_variables.scss:$monospace:             Menlo, Consolas, monospace;`

On `v1.9.1` it was not present yet, but was added by Garee@8733da6f452f7fe1ab7f269700a64854e453d2e1 8 months ago.

**Comment by wigile** [comment]
@jrbenito , thank you, it has worked. #
