### ISSUE TITLE
Code block's word wrap bug

### ISSUE THREAD

**Issue by skout90** [LouisBarranqueiro/hexo-theme-tranquilpeak#428]
### Configuration

![image](https://user-images.githubusercontent.com/11787240/28669324-ce5f56a2-730e-11e7-9115-48fb39f1a25a.png)

when my window width size is about 850px, code block become broken.
this code.
````html
<div>
  <input type="text" id="mainDiseaseCd" required [(ngModel)]="model.mainDiseaseCd">
</div>
````
 
look in my blog link at Step 4
https://skout90.github.io/2017/07/14/Angular/8.%20Angular%20%ED%8F%BC/

** It happend only chrome and safari. in Firefox, IE11 didnt happend**

 - **Operating system with version** : Window 7
 - **Node version** : 6.11.0
 - **Hexo version** : 3.3.7
 - **Hexo-cli version** : 1.0.3
 - **Tranquilpeak version** : modified, 1.10.0

**Comment by LouisBarranqueiro** [comment]
Hi @skout90, I guess this happens because it's not a valid HTML code, the parser do not understand angular properties in the HTML. You can try to not specify the language; like that, highlight.js (the code parser) will interpret your code as a text file but you will loose the syntax coloration. You can create an issue on highlight.js github repo.

Also could you please give me the source code of your article?

**Comment by skout90** [comment]
@LouisBarranqueiro Thanks you!  I posted issue on hightlight.js github repo. https://github.com/isagalaev/highlight.js/issues/1584
