### ISSUE TITLE
Theme won't load the resources CSS and JS in production but works fine on localhost.

### ISSUE THREAD

**Issue by javidrashid** [LouisBarranqueiro/hexo-theme-tranquilpeak#443]
I am having issues with this theme, It looks like it is not a problem with the hexo itself, can you please help with the following issue.

https://github.com/hexojs/hexo/issues/2766

**Comment by LouisBarranqueiro** [comment]
:wave: @javidrashid, please follow the template to post an issue otherwise it hard for me to help you. I quickly read your issue. and you basically need to install theme dependencies and build the theme.
Read:
- https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#installation
- https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#register-tasks
