### ISSUE TITLE
Render Blocking CSS

### ISSUE THREAD

**Issue by anbuchelva** [LouisBarranqueiro/hexo-theme-tranquilpeak#483]
### Configuration

 - **Operating system with version** : All
 - **Node version** :  All
 - **Hexo version** : All
 - **Hexo-cli version** : All 
 - **Tranquilpeak version** : Not modified
 

### Actual behavior
PSI estimates this page requires 1 additional round trips to load render blocking resources and 0.3 MB to fully render. The median page requires 4 round trips and 3.4 MB. Fewer round trips and bytes results in faster pages.

__Eliminate render-blocking JavaScript and CSS in above-the-fold content__ in [google page insights](https://developers.google.com/speed/pagespeed/insights/)

Your page has 1 blocking CSS resources. This causes a delay in rendering your page.
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.
Optimize CSS Delivery of the following:
https://tsttc.pw/…q3faxoaje556v8zc9xcbu7w6f664dv2q.min.css

### Expected behavior

Recommendations from google is [here](https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery)

### Steps to reproduce the behavior
Check the speed test from google page insights.

**Comment by LouisBarranqueiro** [comment]
👋 @anbuchelva 

It looks completely normal to me. Do you have a real issue behind this? 

This tool gives you guidelines to optimize pages loading time. Here, it tells you pages need a CSS file before rendering; which make sense because we don't want to display pages without any CSS. You can't remove this warning because your site has at least one main CSS file which is required before rendering. 

In our case (static site), an option would be to include this CSS file on each page but it will increase size of each page so it does not worth it. For now, we download this CSS file one time and cache it so it's definitely better IMO.

**Comment by venbaa** [comment]
I'm a noob user, have very little knowledge developing web pages.

when i check the google page [insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftsttc.pw&tab=desktop), i get 94/100 for mobile and 96/100 for desktop, which is very good. However, i wanted to increase the page score further, for which i have raised this issue.

Pls close, if it is normal.
thanks for your support.

**Comment by anbuchelva** [comment]
I'm a noob user, have very little knowledge developing web pages.

when i check the [google page insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftsttc.pw&tab=mobile), i get 94/100 for mobile and 96/100 for desktop, which is very good. However, i wanted to increase the page score further, for which i have raised this issue.

Pls close, if it is normal.
thanks for your support.

**Comment by LouisBarranqueiro** [comment]
yes, it's completely normal :)
