### ISSUE TITLE
Demo Site Links Broken

### ISSUE THREAD

**Issue by bmitchinson** [LouisBarranqueiro/hexo-theme-tranquilpeak#515]
### Actual behavior
https://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2014/10/29/Tags-plugins-showcase/#jsFiddle

* The jsFiddle section on the demo site implements a jsFiddle tag that isn't working?
* In addition, the "image" section's link to how to use the image tag in the documentation is damaged.

### Expected behavior
Proper links

### Steps to reproduce the behavior
Visit the demo site and see.

Are you the only one with access to the demo site? Otherwise, I would have offered to fix it, but I don't see it on your public repo list? It has to be public if it's GitHub pages though right?
I feel like it's most likely in this repo and I just don't understand where the page contents are 🤔

**Comment by LouisBarranqueiro** [comment]
👋 @bmitchinson , thanks for letting me know. I will take care of that 👍

**Comment by bmitchinson** [comment]
@LouisBarranqueiro thanks!

Would you consider moving this information to a site that's open source? Then we could update it as needed.

**Comment by LouisBarranqueiro** [comment]
It's open sourced here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/tree/source-blog-posts

but I take care of deploying the demo website, this branch is just read-only.

This happens because the GH pages are under HTTPS and the JSFiddle iframe is under HTTP so it's blocked. I'm gonna PR on Hexo to fix `jsfiddle` Hexo tag.

**Comment by bmitchinson** [comment]
oh great, thanks for filling me in. can u link that PR?
