### ISSUE TITLE
Lazyload images

### ISSUE THREAD

**Issue by fletchto99** [LouisBarranqueiro/hexo-theme-tranquilpeak#532]
Currently loading a blog post with many images can take quite some time to load. I think it would be ideal to lazy-load images in the fancybox gallery at the end. For example my post: https://blog-test.fletchto99.com/2019/april/tomorrowland/ takes ~10s to load. I could probably shrink the images down to allow for faster load times but I think lazy loading would also be ideal. I'll see if I can get around to this sometime in the next week or so and submit a PR.

**Comment by LouisBarranqueiro** [comment]
👋 @fletchto99, thanks for pointing that out. I'm working on an improvement right now. 

On this [page](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fblog-test.fletchto99.com%2F2019%2Fapril%2Ftomorrowland%2F), the gallery contains 41 images and even if the gallery preview displays 3 images maximum, the theme still renders an `img` tag for each images. With the new version only 3 images will be rendered and loaded instead of 41 when the page initially loads. It should make a huge difference. In your case, I also suggest you to use thumbnails and improve compression of your images. You can see more here: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fblog-test.fletchto99.com%2F2019%2Fapril%2Ftomorrowland%2F

**Comment by fletchto99** [comment]
I do believe this post is using thumbnail images however I'll wait for this change to be merged into master and I'll test it out.

**Comment by fletchto99** [comment]
I think something like https://github.com/Robin-front/hexo-lazyload would be pretty cool. I might give this a shot as well. I'll see how difficult it is to integrate into the theme.

**Comment by LouisBarranqueiro** [comment]
> I think something like https://github.com/Robin-front/hexo-lazyload would be pretty cool. I might give this a shot as well. I'll see how difficult it is to integrate into the theme.

The most appropriate way to add such a feature would be to improve the `image` and `video` tag. We don't need a hexo plugin for that. I will take a look at that soon.
