### ISSUE TITLE
Adding wordcount & readtime

### ISSUE THREAD

**Issue by fletchto99** [LouisBarranqueiro/hexo-theme-tranquilpeak#539]
My [blog](https://blog.fletchto99.com/) uses a modified version of this theme which supports [hexo-wordcount](https://github.com/willin/hexo-wordcount) and shows the number of words as well as the time it takes to read the post. If you think this would be a cool feature to add I could set it up as a configuration option and submit a PR.

Here's an example (see below the title):

![Screen Shot 2019-05-26 at 3 33 14 PM](https://user-images.githubusercontent.com/718681/58387458-98ca6380-7fcb-11e9-98c1-2a66aa33a055.png)

**Comment by bmitchinson** [comment]
Oo i love this thank you!

**Comment by LouisBarranqueiro** [comment]
👋 @fletchto99, displaying the number of words is IMO not interesting because the end goal is to have a reading time so users need to do some calculation to know how long it's going to take to read an article -> bad UX. 

Sounds good about the reading time if the implementation is simple and efficient.

**Comment by fletchto99** [comment]
Hmm. I like to display the word count as well, what if we flagged both as an option in the configuration file?

**Comment by bmitchinson** [comment]
I'd also like the word count, so having both in the config file would be preferable imo

**Comment by bmitchinson** [comment]
@fletchto99 What's the status on adding these options to the config file? Debating bringing it into my own site if that's a planned feature.

**Comment by fletchto99** [comment]
I did open https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/pull/541/

I'll get the config stuff sorted out tonight 🎉

**Comment by LouisBarranqueiro** [comment]
@fletchto99  I replied to your PR:
> 👋 @fletchto99, thanks for having taken the time to work on that, unfortunately, I can't accept this PR for several reasons but the main one is that the theme support several languages and the implementation only support Chinese and English. Each feature we add to the theme needs to work along with existing features. This feature will create support because of inaccurate reading time. Also, directly adding code responsible for counting counts and calculate reading time, will give me more things to maintain and I don't want to.
> 
> So far, nobody else asked for this feature, so this is another reason to wait and get more feedback to take the right decision with the right implementation.
> 
> If there are more users asking for it and we can implement a solution that works correctly for all supported languages, then we will add it. If we cannot find a way to automatically calculate the reading time, we could add a `reading_time` variable in the front-matter of each post so users can manually add the reading time of their posts.

Also regarding your point (@fletchto99):
> Hmm. I like to display the word count as well, what if we flagged both as an option in the configuration file?

I understand and that's why I open-sourced this theme so you can do what you want with it. However, I don't want to add this feature into the theme because :
- it does not improve UX
- only you asked for this. I can't add every single feature people want otherwise at the end of the day, the theme will no longer be minimalist and simple to use. New features need to be highly requested by users.
- Related to the previous reason. All these new features need to be maintained so I only want to maintain what's important.

I'm closing this issue in favor of https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/554 so we can track requests.
