### ISSUE TITLE
Ease-in animation of sidebar is not quite like hugo-version tranquilpeak

### ISSUE THREAD

**Issue by DonkeyBear** [LouisBarranqueiro/hexo-theme-tranquilpeak#702]
### Description

As the title, sidebar's ease-in animation is not quite like hugo-version.

### Explanation / motivation

It's not a big deal, but I like hugo-version's animaiton more, if anyone could fix it, that will be help.

**Comment by LouisBarranqueiro** [comment]
👋 @DonkeyBear , could please provide videos, or links so I can see that? I can have a look at it but in the end, hugo theme is imitating hexo theme, not the opposite, and they are not the same.

**Comment by DonkeyBear** [comment]
Hi @LouisBarranqueiro, I'm sorry for confusing the relationship between Hexo and Hugo version.
And I do have GIFs of comparison this time, please take a look:
https://imgur.com/a/vuKUmp1

I'll be glad if Hexo version can add ease animation from Hugo version, thank you.

**Comment by LouisBarranqueiro** [comment]
👋  @DonkeyBear , sorry I will not make that change because that's your personal preference. The theme is open source so you can easily get download it and modify it yourself. 🙂 Here is the code you need to modify: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/source/_css/layouts/_sidebar.scss#L12 and here the procedure to modify the theme: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/DOCUMENTATION.md#modifying-the-theme

**Comment by DonkeyBear** [comment]
@LouisBarranqueiro, Got it. Thanks for your reply, I will learn how to modify this theme, and thank you for bringing us this great theme.
Sincerely.
